---
title: "cellCounter Vignette"
author: "Jianhong Ou, Yanchao Han"
date: "`r doc_date()`"
package: "`r pkg_ver('cellCounter')`"
abstract: >
  Count the cells from a single frame or a z-stack image file and output xml for imageJ
vignette: >
  %\VignetteIndexEntry{cellCounter Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document
---

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
    library(cellCounter)
})
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

# Introduction

```{r, eval=FALSE}
library(EBImage)
library(cellCounter) ## must load EBImage first.
files <- dir("../../others/sample/v", full.names = TRUE)[1:10]
img2 <- readListImg(files)
## detect the cells, time comsuming, please try to run on cluster.
nmask.red <- lapply(img2, function(img){
  Image2(detectObjects3(channel(img, "red")))
})
nmask.green <- lapply(img2, function(img){
  Image2(detectObjects3(channel(img, "green")))
})

red.cells <- labeledImage2Cell(nmask.red, colorChannel="red")
green.cells <- labeledImage2Cell(nmask.green, colorChannel="blue")
cells <- setParentOfCells(c(red.cells, green.cells))
ol <- overlayDetections(img2, cells)
display(ol)
cellTbl <- outputCellTable(cells)
```


# Session Info
```{r sessionInfo, results='asis'}
sessionInfo()
```
